// Generates the Material Design 3 color-token layer from a single seed color.
//
// Usage:  node scripts/generate-theme.mjs [seedHex]
// Example: node scripts/generate-theme.mjs "#006A6A"
//
// Emits app/theme.css with every MD3 color role (light + dark), derived from
// authentic HCT tonal palettes. Change the seed and rerun to re-theme the site.

import { themeFromSourceColor, argbFromHex, hexFromArgb } from "@material/material-color-utilities";
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

// Optimixed brand seed (teal). Override via CLI arg.
const SEED = process.argv[2] ?? "#006A6A";

const theme = themeFromSourceColor(argbFromHex(SEED));
const p = theme.palettes; // primary, secondary, tertiary, neutral, neutralVariant, error

const hex = (palette, tone) => hexFromArgb(palette.tone(tone));

// Canonical MD3 tone assignments: [lightTone, darkTone]
function roles(mode) {
  const i = mode === "light" ? 0 : 1;
  const t = (pal, tones) => hex(pal, tones[i]);
  return {
    "primary": t(p.primary, [40, 80]),
    "on-primary": t(p.primary, [100, 20]),
    "primary-container": t(p.primary, [90, 30]),
    "on-primary-container": t(p.primary, [10, 90]),
    "secondary": t(p.secondary, [40, 80]),
    "on-secondary": t(p.secondary, [100, 20]),
    "secondary-container": t(p.secondary, [90, 30]),
    "on-secondary-container": t(p.secondary, [10, 90]),
    "tertiary": t(p.tertiary, [40, 80]),
    "on-tertiary": t(p.tertiary, [100, 20]),
    "tertiary-container": t(p.tertiary, [90, 30]),
    "on-tertiary-container": t(p.tertiary, [10, 90]),
    "error": t(p.error, [40, 80]),
    "on-error": t(p.error, [100, 20]),
    "error-container": t(p.error, [90, 30]),
    "on-error-container": t(p.error, [10, 90]),
    "background": t(p.neutral, [99, 6]),
    "on-background": t(p.neutral, [10, 90]),
    "surface": t(p.neutral, [99, 6]),
    "on-surface": t(p.neutral, [10, 90]),
    "surface-variant": t(p.neutralVariant, [90, 30]),
    "on-surface-variant": t(p.neutralVariant, [30, 80]),
    "surface-dim": t(p.neutral, [87, 6]),
    "surface-bright": t(p.neutral, [98, 24]),
    "surface-container-lowest": t(p.neutral, [100, 4]),
    "surface-container-low": t(p.neutral, [96, 10]),
    "surface-container": t(p.neutral, [94, 12]),
    "surface-container-high": t(p.neutral, [92, 17]),
    "surface-container-highest": t(p.neutral, [90, 22]),
    "outline": t(p.neutralVariant, [50, 60]),
    "outline-variant": t(p.neutralVariant, [80, 30]),
    "inverse-surface": t(p.neutral, [20, 90]),
    "inverse-on-surface": t(p.neutral, [95, 20]),
    "inverse-primary": t(p.primary, [80, 40]),
    "surface-tint": t(p.primary, [40, 80]),
    "scrim": t(p.neutral, [0, 0]),
    "shadow": t(p.neutral, [0, 0]),
  };
}

const toBlock = (obj) =>
  Object.entries(obj)
    .map(([k, v]) => `  --md-sys-color-${k}: ${v};`)
    .join("\n");

const light = roles("light");
const dark = roles("dark");

const css = `/* AUTO-GENERATED by scripts/generate-theme.mjs — do not edit by hand.
   Material Design 3 color roles derived from seed ${SEED}.
   Regenerate: npm run theme -- "#YOURHEX" */

:root {
${toBlock(light)}
}

/* Follow the OS setting by default... */
@media (prefers-color-scheme: dark) {
  :root {
${toBlock(dark)}
  }
}

/* ...but an explicit data-theme attribute always wins (manual toggle). */
:root[data-theme="light"] {
${toBlock(light)}
}

:root[data-theme="dark"] {
${toBlock(dark)}
}
`;

mkdirSync(join(root, "app"), { recursive: true });
writeFileSync(join(root, "app", "theme.css"), css, "utf8");
console.log(`✓ Wrote app/theme.css from seed ${SEED}`);
